import hr_payment_mode
import paie
import etat_salaire
import cnaps
import ostie
import irsa
import resource_calendar
import cnaps_reportexcel
import employee
import ostie_repeortexcel
import company
import hr_holidays
import irsa_reportexcel
import message_
